export const DI_TOKENS = {
  // Repositories
  MENU_REPOSITORY: Symbol.for("MENU_REPOSITORY"),
  ORDER_REPOSITORY: Symbol.for("ORDER_REPOSITORY"),
  RESERVATION_REPOSITORY: Symbol.for("RESERVATION_REPOSITORY"),
  INVENTORY_REPOSITORY: Symbol.for("INVENTORY_REPOSITORY"),
  STAFF_REPOSITORY: Symbol.for("STAFF_REPOSITORY"),
  TABLE_REPOSITORY: Symbol.for("TABLE_REPOSITORY"),
  INVOICE_REPOSITORY: Symbol.for("INVOICE_REPOSITORY"),
  AUTH_REPOSITORY: Symbol.for("AUTH_REPOSITORY"),
  CUSTOMER_REPOSITORY: Symbol.for("CUSTOMER_REPOSITORY"),
  CATEGORY_REPOSITORY: Symbol.for("CATEGORY_REPOSITORY"),
  MENU_ITEM_REPOSITORY: Symbol.for("MENU_ITEM_REPOSITORY"),
  SETTINGS_REPOSITORY: Symbol.for("SETTINGS_REPOSITORY"),
  LANDING_REPOSITORY: Symbol.for("LANDING_REPOSITORY"),

  // Remote DataSources
  MENU_REMOTE_DATASOURCE: Symbol.for("MENU_REMOTE_DATASOURCE"),
  ORDER_REMOTE_DATASOURCE: Symbol.for("ORDER_REMOTE_DATASOURCE"),
  RESERVATION_REMOTE_DATASOURCE: Symbol.for("RESERVATION_REMOTE_DATASOURCE"),
  INVENTORY_REMOTE_DATASOURCE: Symbol.for("INVENTORY_REMOTE_DATASOURCE"),
  STAFF_REMOTE_DATASOURCE: Symbol.for("STAFF_REMOTE_DATASOURCE"),
  TABLE_REMOTE_DATASOURCE: Symbol.for("TABLE_REMOTE_DATASOURCE"),
  INVOICE_REMOTE_DATASOURCE: Symbol.for("INVOICE_REMOTE_DATASOURCE"),
  AUTH_REMOTE_DATASOURCE: Symbol.for("AUTH_REMOTE_DATASOURCE"),
  CUSTOMER_REMOTE_DATASOURCE: Symbol.for("CUSTOMER_REMOTE_DATASOURCE"),

  // Local DataSources
  MENU_LOCAL_DATASOURCE: Symbol.for("MENU_LOCAL_DATASOURCE"),
  ORDER_LOCAL_DATASOURCE: Symbol.for("ORDER_LOCAL_DATASOURCE"),
  AUTH_LOCAL_DATASOURCE: Symbol.for("AUTH_LOCAL_DATASOURCE"),

  // HTTP
  HTTP_CLIENT: Symbol.for("HTTP_CLIENT"),
  API_BASE_URL: Symbol.for("API_BASE_URL"),
} as const;

export type DiToken = (typeof DI_TOKENS)[keyof typeof DI_TOKENS];
